name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - uses: actions/checkout@v4

      # Configura el JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Instala dependencias y compila el proyecto con Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Ejecuta las pruebas unitarias
      - name: Run tests
        run: mvn test

      # (Opcional) Genera un reporte de cobertura con JaCoCo
      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report
